version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env  
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQLDB_LOCAL_PORT=${MYSQLDB_LOCAL_PORT}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:3306"  
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file:
      - .env  
    ports:
      - "${NODE_DOCKER_PORT}:${NODE_LOCAL_PORT}"  
    environment:
      - DB_HOST=mysqldb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    stdin_open: true
    tty: true

volumes: 
  db:
